# DO NOT DELETE

Log.o: include/Log.hh /usr/include/string.h /usr/include/features.h
Log.o: /usr/include/stdc-predef.h /usr/include/xlocale.h /usr/include/time.h
Log.o: /usr/include/unistd.h /usr/include/getopt.h include/Represent.hh
Log.o: include/RWLock.hh include/Semaphore.hh
Util.o: include/Log.hh /usr/include/string.h /usr/include/features.h
Util.o: /usr/include/stdc-predef.h /usr/include/xlocale.h /usr/include/time.h
Util.o: /usr/include/unistd.h /usr/include/getopt.h include/Represent.hh
Util.o: include/RWLock.hh include/Semaphore.hh include/Util.hh
Util.o: /usr/include/signal.h /usr/include/stdio.h /usr/include/libio.h
Util.o: /usr/include/_G_config.h /usr/include/wchar.h /usr/include/fcntl.h
