# DO NOT DELETE

Log.o: include/Log.hh /usr/include/string.h /usr/include/time.h
Log.o: /usr/include/features.h /usr/include/stdc-predef.h
Log.o: /usr/include/unistd.h include/Represent.hh include/RWLock.hh
Log.o: include/Semaphore.hh
Util.o: include/Log.hh /usr/include/string.h /usr/include/time.h
Util.o: /usr/include/features.h /usr/include/stdc-predef.h
Util.o: /usr/include/unistd.h include/Represent.hh include/RWLock.hh
Util.o: include/Semaphore.hh include/Util.hh /usr/include/signal.h
Util.o: /usr/include/stdio.h /usr/include/fcntl.h
